#!/usr/bin/env python3

import os, sys

# Add the following path auto-generated by CMake.
# This lets you import lilwil without installing it in your Python site-packages
if '@LILWIL_DEFAULT_PYTHON_PATH@'[0] != '@':
    sys.path.append('@LILWIL_DEFAULT_PYTHON_PATH@')
if '@LILWIL_DEFAULT_LIBRARY_PATH@'[0] != '@':
    sys.path.append('@LILWIL_DEFAULT_LIBRARY_PATH@')

# The following may help if the shared library lives in the same directory as this executable
sys.path.append(os.path.dirname(__file__))

from lilwil import cli

lib_name = '@LILWIL_DEFAULT_LIBRARY_NAME@'

if lib_name[0] == '@':
    lib_name = ''

if __name__ == '__main__':
    # Build the parser using the above defaults
    parser = cli.parser(prog=os.path.basename(__file__), lib=lib_name)

    # Example to add your own custom arguments
    # parser.add_argument('--time', type=float, default=float('inf'), help='maximum test time')

    # Parse command line arguments
    args = vars(parser.parse_args())

    # Import the library that was deduced
    lib = cli.import_library(args['lib'])

    # Example to apply your own arguments to the test suite
    # lib.add_value('max_time', args.pop('time'))

    # Call the underlying implementation and exit (use cli.main to run but not exit)
    cli.exit_main(**args)
